### PR TITLE
Add SLE binaries in the buildpack

### PR DESCRIPTION
**Pull request by jimmykarily**
Signed-off-by: André Duffeck <aduffeck@suse.com>

### CODE REVIEW

**Comment by alexjh** [comment]
@jimmykarily @aduffeck 

The short SHA in the filename `go_buildpack-cached-v1.8.4-3c6e3b1.zip` and the SHA listed don't match: `c6ef4fe309e6944437eacd4608da1e2ae3ac8a19`.

It's not absolutely required, but I'd like to know what happened in case the docs were unclear, etc. In order to get the release done, I'm inclined to fix this during NA hours and have someone else review. It would mean renaming the file in the S3 bucket, and updating this PR. 

The other buildpack PRs look good. :+1:

**Comment by jimmykarily** [comment]
ok it is fixed now.

**Comment by aduffeck** [comment]
I just looked at the console history and I think I know what happened: we ran `LONGSHA1SUM=$(s3cmd get "${CANDIDATE}" - | sha1sum | awk '{print $1}')` like in the docs and it succeeded. But instead of running the next command we (as in `I` :) ) accidentally ran this first command again and canceled it quickly. Apparently it still overwrote the content of the variable with a wrong checksum, although we even did a quick test which seemed to indicate that it wouldn't do that.

HTH.

**Review by alexjh — APPROVED** [review]
LGTM

**Pull request merged**
